# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('content', models.TextField()),
                ('draft', models.BooleanField(default=False)),
                ('email', models.EmailField(default='please_change@gmail.com', max_length=220)),
            ],
        ),
    ]
